fix hardhat & add foundry examples
neonlabsorg/neon-evm.docs pull request #110
Opened 2023-11-16 06:15 UTC by mnedelchev-vn

Hi @m4sterbunny @0xlucian @sukanyaparashar please have a look at this PR:

1. Edited Hardhat Example
2. Added Foundry Example
3. Add the foundry example to sidebar.js

2023-11-16 13:07 UTC, m4sterbunny commented on docs/developing/connect_rpc.md
> +comment: todo Find out from Yury whether we can have a NeonLabs youtube domain to support the video material that has been created to complement this page
@YYYurchenko I created video material that supports this page. Once it is clear who has mandate for docs pages, if it is still product, then I want to link to that video support

2023-11-21 09:50 UTC, m4sterbunny commented
@mnedelchev-vn There are conflicts on this branch since merging other branches PTAL

2023-11-21 10:24 UTC, mnedelchev-vn commented
@m4sterbunny the conflict in this branch is made by you, because you've changed file `static/data/link-list.json` which was recently updated in the `main` branch. I guess undo your change and it include it in a separated PR.

2023-11-21 10:58 UTC, m4sterbunny commented
@mnedelchev-vn confused! GitHub says that these are the conflicting files:
<img width="592" alt="image" src="https://github.com/neonlabsorg/neon-evm.docs/assets/20266893/2ef6952d-24c7-4c50-ba32-38b966c25eb6">

2023-11-21 10:58 UTC, m4sterbunny commented
none of which are a json file

2023-11-21 12:35 UTC, m4sterbunny commented
@mnedelchev-vn I have fixed the conflicts -- there are 2 items pending with you. PTAL and ping me when done.

2023-11-24 16:00 UTC, m4sterbunny requested changes
finish the review idiot

2023-11-24 19:53 UTC, mnedelchev-vn commented on docs/developing/deploy_facilities/using_foundry.md
> +<!-- I suspect there is no need to create new wallet as per first draft of page >> existing wallet probably fine -- test on run through -->
@m4sterbunny I'm not happy with the way you cut the example of using foundry. Currently in file [docs/developing/deploy_facilities/using_foundry.md](https://github.com/neonlabsorg/neon-evm.docs/pull/110/files/2765014529675ed3f9dbe47955944a6a8eaffee3#diff-a844f10ba30859fca4e55caa4193c1ece97430b551fdfb0ae3e69c24d768915d) you've left only one step which is the deployment of the contract. We need back:
1. Installation step
2. Setup of the environment file
3. Compile contracts
4. Deploy contracts
5. Verify contracts

Plus the verification with foundry is a lot different than verification with hardhat so it has to be explained here in detail also. If you want to shorten my initial file then remove the MetaMask info from step 2, but anything else is important to have.

2023-11-28 10:59 UTC, m4sterbunny commented on docs/developing/deploy_facilities/using_foundry.md
> +<!-- I suspect there is no need to create new wallet as per first draft of page >> existing wallet probably fine -- test on run through -->
@mnedelchev-vn I assume that you are a little git confused -- GitHub does not provide the easiest UX, and you would probably enjoy using the competitors. I have pulled this branch (1) and am looking at the file using_foundry.md (2) I see Step 1 (3) 
![image](https://github.com/neonlabsorg/neon-evm.docs/assets/20266893/e4ee5de0-8eb3-4f39-896b-a4bb85ba3368)
Step 2
![image](https://github.com/neonlabsorg/neon-evm.docs/assets/20266893/b1b97585-c487-442e-8e07-e7305ef76f0f)

Step 3 
![image](https://github.com/neonlabsorg/neon-evm.docs/assets/20266893/47e78ebb-40ac-4fc5-aaa1-6c61cbcca255)

Step 4
![image](https://github.com/neonlabsorg/neon-evm.docs/assets/20266893/a7763e18-a580-489d-a0e9-c2a891c57b66)

Step 5
![image](https://github.com/neonlabsorg/neon-evm.docs/assets/20266893/21edb30b-d6b0-4211-95dc-95b61e4106ae)

If you need help pulling a branch locally that has been changed remotely -- give me a shout and I can show you how

2023-11-29 23:36 UTC, mnedelchev-vn commented on docs/developing/deploy_facilities/using_foundry.md
> +<!-- I suspect there is no need to create new wallet as per first draft of page >> existing wallet probably fine -- test on run through -->
> @m4sterbunny I'm not happy with the way you cut the example of using foundry. Currently in file [docs/developing/deploy_facilities/using_foundry.md](https://github.com/neonlabsorg/neon-evm.docs/pull/110/files/2765014529675ed3f9dbe47955944a6a8eaffee3#diff-a844f10ba30859fca4e55caa4193c1ece97430b551fdfb0ae3e69c24d768915d) you've left only one step which is the deployment of the contract. We need back:
> 
> 1. Installation step
> 2. Setup of the environment file step
> 3. Compile contracts step
> 4. Deploy contracts step
> 5. Verify contracts step
> 
> Plus the verification with foundry is a lot different than verification with hardhat so it has to be explained here in detail also. If you want to shorten my initial file then remove the MetaMask info from step 2, but anything else is important to have.

@m4sterbunny nvm this.

2023-11-29 23:37 UTC, mnedelchev-vn commented on docs/developing/deploy_facilities/using_foundry.md
> +<!-- I don't see this step: You test this contract by transferring tokens to randomly generated wallet. todo verify if this can be added, or if I missed it -->
We don't have this example inside the foundry github repo.

2023-11-29 23:39 UTC, mnedelchev-vn commented
@m4sterbunny there was some wrong stuff with `using_hardhat.mdx` file, for whatever reason the content was a real mess. I made a new commit where I recreated the steps to deploy thru hardhat. Please check Hardhat & Foundry pages and lmk if we missed smth.

2023-12-05 10:26 UTC, m4sterbunny commented on docs/developing/deploy_facilities/using_foundry.md
> +<!-- I don't see this step: You test this contract by transferring tokens to randomly generated wallet. todo verify if this can be added, or if I missed it -->
I am deleting the unsupported step

2023-12-05 10:29 UTC, m4sterbunny approved these changes
I did DIY review fixes as this languished too long

2023-12-05 10:29 UTC, merged