Fix/integrate section
neonlabsorg/neon-evm.docs pull request #93
Opened 2023-11-02 09:00 UTC by mnedelchev-vn

Hi @m4sterbunny @sukanyaparashar @0xlucian ,
this PR includes Docs changes inside **Integrate** section and more specifically **WalletConnect**, **MetaMask** and **Chainlink**. I haven't changed anything into **The Graph** & **Pyth** pages, because I made a task for the changes there to @m4sterbunny and by the time I made it I had no idea that we will be updating the whole documentation soon. lmk if you see smth wrong, thanks

2023-11-16 06:21 UTC, mnedelchev-vn commented
@m4sterbunny please don't miss this one, thank you!

2023-11-17 15:49 UTC, m4sterbunny requested changes

2023-11-17 15:49 UTC, m4sterbunny commented on docs/developing/integrate/wallets/integrating_walletconnect.mdx
> +3.6 Run command `npm run dev` to start your Web application and you should see the Web3Modal button loaded in your Web app page.
@mnedelchev-vn previously you used tabs to support yarn command -- pls extend same support here

2023-11-17 15:49 UTC, m4sterbunny commented on docs/developing/integrate/wallets/integrating_walletconnect.mdx
> +<img src={walletconnectqr} width="300" />
Can you cut your images closer to remove the grey background (or post-process it gone)?

2023-11-17 15:56 UTC, m4sterbunny commented
@mnedelchev-vn Pls review my commit that aligns with style, hopefully as you see more of these, the style will become 2nd nature -- if not -- [Google Developer Style Guide](https://developers.google.com/style) is your friend!

2023-11-21 10:57 UTC, mnedelchev-vn commented
I'm ok with the changes, however I got 2 questions for you:
1. I saw you changed **DevNet** to **Devnet**, well then if you're not happy with this **DevNet** naming you should also contact whoever listed us in [Chainlist](https://chainlist.org/?search=Neon&testnets=true) to change the names also there?
2. I saw you've placed **an** before consonant, is this correct? Example - _For this guide, we are configuring an HTML Web App._

2023-11-21 17:01 UTC, m4sterbunny commented
1. Yes [our style is Devnet](https://github.com/neonlabsorg/neon-evm.docs/blob/fb7782735f4adc4265e2123172239e2b9920105e/.github/styles/Grammarly.csv#L34) -- Please follow the Dali Lama and be the change you want == do find out how to get Chainlist to update to our style 
2. I wish English were easier on the non-natives, perhaps read this: https://www.writing-skills.com/hit-or-myth-use-an-before-h-words

2023-11-21 17:02 UTC, m4sterbunny commented on docs/developing/integrate/wallets/integrating_walletconnect.mdx
> +<img src={walletconnectqr} width="300" />
@mnedelchev-vn PTAL at this request

2023-11-21 17:03 UTC, m4sterbunny commented
@mnedelchev-vn  there are some requested changes on the review that I conducted for you, please can you address those so that we can progress this PR. Thanks.

2023-11-23 15:20 UTC, mnedelchev-vn commented
@m4sterbunny hey, I've added the requested changes, please check them.

2023-11-24 16:02 UTC, m4sterbunny commented on docs/developing/integrate/wallets/integrating_walletconnect.mdx
> +<img src={walletconnectqr} width="300" />
done

2023-11-24 16:27 UTC, m4sterbunny approved these changes

2023-11-24 16:27 UTC, m4sterbunny commented
LGTM

2023-11-24 16:27 UTC, merged